package ai

import "github.com/SuryaTK2007/DriftShield/internal/types"

// GeneratedRecommendations represents the response from the LLM.
type GeneratedRecommendations struct {
	// A list of recommendations explained to the user.
	Recommendations []Recommendation `json:"recommendations"`

	// The generated baseline configuration based on user input and recommendations.
	Baseline GeneratedBaseline `json:"baseline"`
}

// Recommendation explains a security decision.
type Recommendation struct {
	Action      string `json:"action"`      // e.g. "Enable S3 Block Public Access"
	Explanation string `json:"explanation"` // e.g. "Because you are hosting internal assets, public access should be strictly blocked."
}

// GeneratedBaseline is the unified baseline configuration generated by the AI.
type GeneratedBaseline struct {
	S3         *types.S3Baseline         `json:"s3"`
	EC2        *types.EC2Baseline        `json:"ec2"`
	IAM        *types.IAMBaseline        `json:"iam"`
	CloudTrail *types.CloudTrailBaseline `json:"cloudtrail"`
	VPC        *types.VPCBaseline        `json:"vpc"`
	RDS        *types.RDSBaseline        `json:"rds"`
}
